apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # googleCloudBuild:
  #   projectId: ticketing-dev-314218
  local:
    push: true
  artifacts:
    # - image: eu.gcr.io/ticketing-dev-314218/auth
    - image: levandocker321/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .